# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# Google Analytics tracking id
google_analytics_id:

# HTML Title
title: "throwingbits"

# Avatar image path
avatar: "./images/profile.jpeg"

# Name section text
name: "@throwingbits"

# Tagline section text
tagline: >-
    An iOS, web, and automation developer from Taiwan ðŸ‡¹ðŸ‡¼ who also loves sharing, traveling, and writing.

socials:
  - social:
      icon: "fa-brands fa-twitch"
      url: "https://www.twitch.tv/throwingbits"
      alt: "throwingbit's Twitch"
      title: "throwingbit's Twitch"
      target: "_blank"
  - social:
      icon: "fa-brands fa-youtube"
      url: ""
      alt: "throwingbit's YouTube"
      title: "throwingbit's YouTube"
      target: "_blank"
  - social:
      icon: "fa-brands fa-instagram"
      url: "https://www.instagram.com/throwingbits"
      alt: "throwingbit's Instagram"
      title: "throwingbit's Instagram"
      target: "_blank"
  - social:
      icon: "fa-brands fa-x-twitter"
      url: "https://x.com/throwingbits"
      alt: "throwingbit's X"
      title: "throwingbit's X"
      target: "_blank"
  - social:
      icon: "fa-brands fa-github"
      url: "https://www.github.com/throwingbits"
      alt: "throwingbit's GitHub"
      title: "throwingbit's GitHub"
      target: "_blank"
      
# Footer copyright message
# Linkyee is a 100% free, open-source projectâ€”feel free to modify the copyright message as you like. :)
copyright: >
  Â© 2024  <a href="https://link.zhgchg.li" target="_blank">ZhgChgLi</a>. Powered by <a href="https://github.com/ZhgChgLi/linkyee" target="_blank">linkyee</a>
