# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: CatppuccinMocha

# HTML Language setting
lang: "en"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# Google Analytics tracking id
google_analytics_id:

# HTML Title
title: "throwingbits"

# Name section text
name: "@throwingbits"

# Avatar image path
avatar: "./images/avatar.webp"

# Tagline section text
tagline: >-
    Software Developer, Streamer and full-time idiot made in üá©üá™ ‚úåÔ∏è

socials:
  - social:
      icon: "fa-brands fa-twitch"
      url: "https://www.twitch.tv/throwingbits"
      alt: "throwingbit's Twitch"
      title: "throwingbit's Twitch"
      target: "_blank"
  - social:
      icon: "fa-brands fa-youtube"
      url: "https://www.youtube.com/@throwingbits"
      alt: "throwingbit's YouTube"
      title: "throwingbit's YouTube"
      target: "_blank"
  - social:
      icon: "fa-brands fa-instagram"
      url: "https://www.instagram.com/throwingbits"
      alt: "throwingbit's Instagram"
      title: "throwingbit's Instagram"
      target: "_blank"
  - social:
      icon: "fa-brands fa-twitter"
      url: "https://x.com/throwingbits"
      alt: "throwingbit's X"
      title: "throwingbit's X"
      target: "_blank"
  - social:
      icon: "fa-brands fa-github"
      url: "https://www.github.com/throwingbits"
      alt: "throwingbit's GitHub"
      title: "throwingbit's GitHub"
      target: "_blank"
